index.html
**Index.html**
- line: 1-55
- build html bones
=> Docs: add html blueprint

index.html, styles.css
**styles.css**
- lines 1 - 61
- align header to center
- align swatch container to main container
- align hex code input and lock button to swatch
- aligned and add buttons - random and save
=> Docs:align header and main html elements

index.html, styles.css
**index.html**
- Line 17 -38
- add lock image- locked
- add lock image -un-locked
- removed-buttons
**styles.css**
- Line 57
- add class .lock size
-Line 61 
- add feat: hover to lock size
-Line 65 -82
- hard code hex# into background
CG
=> Feat: add images and adjust hex-code

classes.js
**classes.js**
- Add class Color
- Add class Palette
- lines: 1-15
=> Docs: add classes.js

index.html, src/Color.js, styles.css
**Feature: CSS & HTML**
- lines: css - 87-90
- lines: html - 14-39
- Refactor the colors and hex ids
=> Feat: Fix css color and html refactor

src/Color.js, src/Palette.js
**Palette.js**
- lines 10-17
- assign 5 new Cover instances to the Palette.colors property.
**Color.js**
=> feat: Add colors to Palette class

index.html, src/Color.js, src/Palette.js, src/scripts.js
**scripts.js**
- add querySelector lines 1-11
- add eventListeners lines 14-15
- add random function lines 16-31
=> Feat: Add randomized palette function

index.html, src/scripts.js
##Add Selectors
**scripts.js
- added selectors lines 11-15 
- added toggle functions lines 23-31
=> Feat: Add selectors

src/scripts.js
**scripts.js**
- added save option to lines 50-55
=> Feature: Add save palette option

index.html, src/scripts.js, styles.css
**index.html**
- added title and figure wrap lines 60 -70
**styles.css**
- resized saved palette section lines 103-122
=> Refactor: mini cover section trashcan

index.html, styles.css
**index.hmtl**
- lines 17-48
- added lock container class to each figure element that contains the lock and unlock images
**styles.css**
-lines 61-68
-added lock container selector and adjusted the locks selector to fit inside in a dynamic way (used %) .
=> Refactor: Adjust locks and lock container to be dynamic with page size

index.html, styles.css
**HTML**
- lines: 69-70
- Added delete palettes button
**CSS**
- lines: 8-18, 111-140
- Added styling gradient to background, animation to buttons, styling to hidden palette section.
=> Feature: Add new css and refactor html

index.html, src/scripts.js
**scripts.js**
- lines 18 - 37, 44-70
- add querys for each lock image
- add toggle in lock and unlock function
**index.html**
- 18-19, 25-26, 32-33, 39-40, 46-47
- add unique lock and unlock id to each lock and unlock image
=> Feature: Add ability to toggle lock and unlock images

index.html, src/scripts.js, styles.css
**css.styles**
- lines: 137-167
- Formatting mini swatchtes
**index.html**
- lines: 62-69
- Refactor html
=> Feat: Updated CSS styling and html on mini swatches

.vscode/settings.json, index.html, src/Color.js, src/Palette.js, src/scripts.js, styles.css
**styles.css**
- Remove lock toggle boxes
**Color.js**
- add lock toggle information
**scripts.js**
- remove lock and un-lock query selctors
- remove lock and unlock variables
- remove commented out code for lock toggle
=> refractor: configure toggle lock

index.html, src/Palette.js, src/scripts.js
**scripts.js**
- added shuffle function lines 25-29
- WIP lock function lines 31-46
=> AFeature: add spacebar shuffle functionality

src/scripts.js
**scripts.js**
- lines: 31-45 
-  Added function for toggle lock, palettes still need to be connected.
=> Feature: Add lock toggle

index.html, src/Color.js, src/Palette.js, src/scripts.js, styles.css
**scripts.js**
- changed function names, separated larger functions, added save ability lines 31-81
=> Feature: add save swatch functionality

.vscode/settings.json, index.html, src/Color.js, src/Palette.js, src/scripts.js, styles.css
**scripts.js**
- added function that prevents duplicate swatches being saved lines 79 - 88
=> Feature: add prevent duplicate swatches function

src/scripts.js
**scripts.js**
- added two functions to delete from array and refresh saved section lines 106-117
=> Feature: add function to delete from array

index.html, src/scripts.js, styles.css
##Refactor html and adjust lock images
**index.html**
-lines 3-69
**styles.css**
-lines 45-53
**scripts.js**
refactored empathetically
=> Refactor: html css scripts to adjsut locks

README.md
**README.md**
- Lines 1-51
- Update README specs for final deployment
=> Feat: update readme

README.md
**main.js**
- ALL
**index.html**
-ALL 
- Testing merge issues
=> Refactor: all
